MERGE INTO Land( LandID,Name)VALUES ('AF','Afghanistan');
MERGE INTO Land( LandID,Name)VALUES ('EG','Ägypten');
MERGE INTO Land( LandID,Name)VALUES ('AL','Albanien');
MERGE INTO Land( LandID,Name)VALUES ('DZ','Algerien');
MERGE INTO Land( LandID,Name)VALUES ('VI','Amerikanische Jungferninseln');
MERGE INTO Land( LandID,Name)VALUES ('AS','Amerikanisch-Samoa');
MERGE INTO Land( LandID,Name)VALUES ('AD','Andorra');
MERGE INTO Land( LandID,Name)VALUES ('AO','Angola');
MERGE INTO Land( LandID,Name)VALUES ('AI','Anguilla');
MERGE INTO Land( LandID,Name)VALUES ('AG','Antigua und Barbuda');
MERGE INTO Land( LandID,Name)VALUES ('GQ','Äquatorialguinea');
MERGE INTO Land( LandID,Name)VALUES ('AR','Argentinien');
MERGE INTO Land( LandID,Name)VALUES ('AM','Armenien');
MERGE INTO Land( LandID,Name)VALUES ('AW','Aruba');
MERGE INTO Land( LandID,Name)VALUES ('AZ','Aserbaidschan');
MERGE INTO Land( LandID,Name)VALUES ('ET','Äthiopien');
MERGE INTO Land( LandID,Name)VALUES ('AU','Australien');
MERGE INTO Land( LandID,Name)VALUES ('BS','Bahamas');
MERGE INTO Land( LandID,Name)VALUES ('BH','Bahrain');
MERGE INTO Land( LandID,Name)VALUES ('BD','Bangladesch');
MERGE INTO Land( LandID,Name)VALUES ('BB','Barbados');
MERGE INTO Land( LandID,Name)VALUES ('BY','Belarus');
MERGE INTO Land( LandID,Name)VALUES ('BE','Belgien');
MERGE INTO Land( LandID,Name)VALUES ('BZ','Belize');
MERGE INTO Land( LandID,Name)VALUES ('BJ','Benin');
MERGE INTO Land( LandID,Name)VALUES ('BM','Bermuda');
MERGE INTO Land( LandID,Name)VALUES ('BT','Bhutan');
MERGE INTO Land( LandID,Name)VALUES ('BO','Bolivien');
MERGE INTO Land( LandID,Name)VALUES ('BQ','Bonaire, Saba, Sint Eustatius');
MERGE INTO Land( LandID,Name)VALUES ('BA','Bosnien und Herzegowina');
MERGE INTO Land( LandID,Name)VALUES ('BW','Botsuana');
MERGE INTO Land( LandID,Name)VALUES ('BR','Brasilien');
MERGE INTO Land( LandID,Name)VALUES ('VG','Britische Jungferninseln');
MERGE INTO Land( LandID,Name)VALUES ('BN','Brunei Darussalam');
MERGE INTO Land( LandID,Name)VALUES ('BG','Bulgarien');
MERGE INTO Land( LandID,Name)VALUES ('BF','Burkina Faso');
MERGE INTO Land( LandID,Name)VALUES ('BI','Burundi');
MERGE INTO Land( LandID,Name)VALUES ('CV','Cabo Verde');
MERGE INTO Land( LandID,Name)VALUES ('CL','Chile');
MERGE INTO Land( LandID,Name)VALUES ('CN','China');
MERGE INTO Land( LandID,Name)VALUES ('CK','Cookinseln');
MERGE INTO Land( LandID,Name)VALUES ('CR','Costa Rica');
MERGE INTO Land( LandID,Name)VALUES ('CI','Côte d Ivoire');
MERGE INTO Land( LandID,Name)VALUES ('CW','Curaçao');
MERGE INTO Land( LandID,Name)VALUES ('DK','Dänemark');
MERGE INTO Land( LandID,Name)VALUES ('DE','Deutschland');
MERGE INTO Land( LandID,Name)VALUES ('DM','Dominica');
MERGE INTO Land( LandID,Name)VALUES ('DO','Dominikanische Republik');
MERGE INTO Land( LandID,Name)VALUES ('DJ','Dschibuti');
MERGE INTO Land( LandID,Name)VALUES ('EC','Ecuador');
MERGE INTO Land( LandID,Name)VALUES ('SV','El Salvador');
MERGE INTO Land( LandID,Name)VALUES ('ER','Eritrea');
MERGE INTO Land( LandID,Name)VALUES ('EE','Estland');
MERGE INTO Land( LandID,Name)VALUES ('SZ','Eswatini');
MERGE INTO Land( LandID,Name)VALUES ('FK','Falklandinseln');
MERGE INTO Land( LandID,Name)VALUES ('FO','Färöer');
MERGE INTO Land( LandID,Name)VALUES ('FJ','Fidschi');
MERGE INTO Land( LandID,Name)VALUES ('FI','Finnland');
MERGE INTO Land( LandID,Name)VALUES ('FR','Frankreich');
MERGE INTO Land( LandID,Name)VALUES ('GF','Französisch-Guayana');
MERGE INTO Land( LandID,Name)VALUES ('PF','Französisch-Polynesien');
MERGE INTO Land( LandID,Name)VALUES ('GA','Gabun');
MERGE INTO Land( LandID,Name)VALUES ('GM','Gambia');
MERGE INTO Land( LandID,Name)VALUES ('GE','Georgien');
MERGE INTO Land( LandID,Name)VALUES ('GH','Ghana');
MERGE INTO Land( LandID,Name)VALUES ('GI','Gibraltar');
MERGE INTO Land( LandID,Name)VALUES ('GD','Grenada');
MERGE INTO Land( LandID,Name)VALUES ('GR','Griechenland');
MERGE INTO Land( LandID,Name)VALUES ('GL','Grönland');
MERGE INTO Land( LandID,Name)VALUES ('GB','Großbritannien');
MERGE INTO Land( LandID,Name)VALUES ('GP','Guadeloupe');
MERGE INTO Land( LandID,Name)VALUES ('GU','Guam');
MERGE INTO Land( LandID,Name)VALUES ('GT','Guatemala');
MERGE INTO Land( LandID,Name)VALUES ('GG','Guernsey');
MERGE INTO Land( LandID,Name)VALUES ('GN','Guinea');
MERGE INTO Land( LandID,Name)VALUES ('GW','Guinea-Bissau');
MERGE INTO Land( LandID,Name)VALUES ('GY','Guyana');
MERGE INTO Land( LandID,Name)VALUES ('HT','Haiti');
MERGE INTO Land( LandID,Name)VALUES ('HN','Honduras');
MERGE INTO Land( LandID,Name)VALUES ('HK','Hongkong');
MERGE INTO Land( LandID,Name)VALUES ('IN','Indien');
MERGE INTO Land( LandID,Name)VALUES ('ID','Indonesien');
MERGE INTO Land( LandID,Name)VALUES ('IM','Insel Man');
MERGE INTO Land( LandID,Name)VALUES ('IQ','Irak');
MERGE INTO Land( LandID,Name)VALUES ('IR','Iran');
MERGE INTO Land( LandID,Name)VALUES ('IE','Irland');
MERGE INTO Land( LandID,Name)VALUES ('IS','Island');
MERGE INTO Land( LandID,Name)VALUES ('IL','Israel');
MERGE INTO Land( LandID,Name)VALUES ('IT','Italien');
MERGE INTO Land( LandID,Name)VALUES ('JM','Jamaika');
MERGE INTO Land( LandID,Name)VALUES ('JP','Japan');
MERGE INTO Land( LandID,Name)VALUES ('YE','Jemen');
MERGE INTO Land( LandID,Name)VALUES ('JE','Jersey');
MERGE INTO Land( LandID,Name)VALUES ('JO','Jordanien');
MERGE INTO Land( LandID,Name)VALUES ('KY','Kaimaninseln');
MERGE INTO Land( LandID,Name)VALUES ('KH','Kambodscha');
MERGE INTO Land( LandID,Name)VALUES ('CM','Kamerun');
MERGE INTO Land( LandID,Name)VALUES ('CA','Kanada');
MERGE INTO Land( LandID,Name)VALUES ('KZ','Kasachstan');
MERGE INTO Land( LandID,Name)VALUES ('QA','Katar');
MERGE INTO Land( LandID,Name)VALUES ('KE','Kenia');
MERGE INTO Land( LandID,Name)VALUES ('KG','Kirgisistan');
MERGE INTO Land( LandID,Name)VALUES ('KI','Kiribati');
MERGE INTO Land( LandID,Name)VALUES ('CC','Kokosinseln (Keelinginseln)');
MERGE INTO Land( LandID,Name)VALUES ('CO','Kolumbien');
MERGE INTO Land( LandID,Name)VALUES ('KM','Komoren');
MERGE INTO Land( LandID,Name)VALUES ('CG','Kongo');
MERGE INTO Land( LandID,Name)VALUES ('CD','Kongo, Demokratische Republik');
MERGE INTO Land( LandID,Name)VALUES ('KP','Korea, Demokratische Volksrepublik');
MERGE INTO Land( LandID,Name)VALUES ('KR','Korea, Republik');
MERGE INTO Land( LandID,Name)VALUES ('HR','Kroatien');
MERGE INTO Land( LandID,Name)VALUES ('CU','Kuba');
MERGE INTO Land( LandID,Name)VALUES ('KW','Kuwait');
MERGE INTO Land( LandID,Name)VALUES ('LA','Laos');
MERGE INTO Land( LandID,Name)VALUES ('LS','Lesotho');
MERGE INTO Land( LandID,Name)VALUES ('LV','Lettland');
MERGE INTO Land( LandID,Name)VALUES ('LB','Libanon');
MERGE INTO Land( LandID,Name)VALUES ('LR','Liberia');
MERGE INTO Land( LandID,Name)VALUES ('LY','Libyen');
MERGE INTO Land( LandID,Name)VALUES ('LI','Liechtenstein');
MERGE INTO Land( LandID,Name)VALUES ('LT','Litauen');
MERGE INTO Land( LandID,Name)VALUES ('LU','Luxemburg');
MERGE INTO Land( LandID,Name)VALUES ('MO','Macau');
MERGE INTO Land( LandID,Name)VALUES ('MG','Madagaskar');
MERGE INTO Land( LandID,Name)VALUES ('MW','Malawi');
MERGE INTO Land( LandID,Name)VALUES ('MY','Malaysia');
MERGE INTO Land( LandID,Name)VALUES ('MV','Malediven');
MERGE INTO Land( LandID,Name)VALUES ('ML','Mali');
MERGE INTO Land( LandID,Name)VALUES ('MT','Malta');
MERGE INTO Land( LandID,Name)VALUES ('MA','Marokko');
MERGE INTO Land( LandID,Name)VALUES ('MH','Marshallinseln');
MERGE INTO Land( LandID,Name)VALUES ('MQ','Martinique');
MERGE INTO Land( LandID,Name)VALUES ('MR','Mauretanien');
MERGE INTO Land( LandID,Name)VALUES ('MU','Mauritius');
MERGE INTO Land( LandID,Name)VALUES ('YT','Mayotte');
MERGE INTO Land( LandID,Name)VALUES ('MX','Mexiko');
MERGE INTO Land( LandID,Name)VALUES ('','Midway');
MERGE INTO Land( LandID,Name)VALUES ('FM','Mikronesien');
MERGE INTO Land( LandID,Name)VALUES ('MD','Moldau');
MERGE INTO Land( LandID,Name)VALUES ('MC','Monaco');
MERGE INTO Land( LandID,Name)VALUES ('MN','Mongolei');
MERGE INTO Land( LandID,Name)VALUES ('ME','Montenegro');
MERGE INTO Land( LandID,Name)VALUES ('MS','Montserrat');
MERGE INTO Land( LandID,Name)VALUES ('MZ','Mosambik');
MERGE INTO Land( LandID,Name)VALUES ('MM','Myanmar');
MERGE INTO Land( LandID,Name)VALUES ('NA','Namibia');
MERGE INTO Land( LandID,Name)VALUES ('NR','Nauru');
MERGE INTO Land( LandID,Name)VALUES ('NP','Nepal');
MERGE INTO Land( LandID,Name)VALUES ('NC','Neukaledonien');
MERGE INTO Land( LandID,Name)VALUES ('NZ','Neuseeland');
MERGE INTO Land( LandID,Name)VALUES ('NI','Nicaragua');
MERGE INTO Land( LandID,Name)VALUES ('NL','Niederlande');
MERGE INTO Land( LandID,Name)VALUES ('NE','Niger');
MERGE INTO Land( LandID,Name)VALUES ('NG','Nigeria');
MERGE INTO Land( LandID,Name)VALUES ('NU','Niue');
MERGE INTO Land( LandID,Name)VALUES ('MP','Nördliche Marianen');
MERGE INTO Land( LandID,Name)VALUES ('MK','Nordmazedonien');
MERGE INTO Land( LandID,Name)VALUES ('NF','Norfolkinsel');
MERGE INTO Land( LandID,Name)VALUES ('NO','Norwegen');
MERGE INTO Land( LandID,Name)VALUES ('OM','Oman');
MERGE INTO Land( LandID,Name)VALUES ('AT','Österreich');
MERGE INTO Land( LandID,Name)VALUES ('PK','Pakistan');
MERGE INTO Land( LandID,Name)VALUES ('PW','Palau');
MERGE INTO Land( LandID,Name)VALUES ('PA','Panama');
MERGE INTO Land( LandID,Name)VALUES ('PG','Papua-Neuguinea');
MERGE INTO Land( LandID,Name)VALUES ('PY','Paraguay');
MERGE INTO Land( LandID,Name)VALUES ('PE','Peru');
MERGE INTO Land( LandID,Name)VALUES ('PH','Philippinen');
MERGE INTO Land( LandID,Name)VALUES ('PN','Pitcairninseln');
MERGE INTO Land( LandID,Name)VALUES ('PL','Polen');
MERGE INTO Land( LandID,Name)VALUES ('PT','Portugal');
MERGE INTO Land( LandID,Name)VALUES ('PR','Puerto Rico');
MERGE INTO Land( LandID,Name)VALUES ('RE','Réunion');
MERGE INTO Land( LandID,Name)VALUES ('RW','Ruanda');
MERGE INTO Land( LandID,Name)VALUES ('RO','Rumänien');
MERGE INTO Land( LandID,Name)VALUES ('RU','Russische Föderation');
MERGE INTO Land( LandID,Name)VALUES ('MF','Saint-Martin');
MERGE INTO Land( LandID,Name)VALUES ('SB','Salomonen');
MERGE INTO Land( LandID,Name)VALUES ('ZM','Sambia');
MERGE INTO Land( LandID,Name)VALUES ('WS','Samoa');
MERGE INTO Land( LandID,Name)VALUES ('SM','San Marino');
MERGE INTO Land( LandID,Name)VALUES ('ST','São Tomé und Príncipe');
MERGE INTO Land( LandID,Name)VALUES ('SA','Saudi-Arabien');
MERGE INTO Land( LandID,Name)VALUES ('SE','Schweden');
MERGE INTO Land( LandID,Name)VALUES ('CH','Schweiz');
MERGE INTO Land( LandID,Name)VALUES ('SN','Senegal');
MERGE INTO Land( LandID,Name)VALUES ('RS','Serbien');
MERGE INTO Land( LandID,Name)VALUES ('SC','Seychellen');
MERGE INTO Land( LandID,Name)VALUES ('SL','Sierra Leone');
MERGE INTO Land( LandID,Name)VALUES ('ZW','Simbabwe');
MERGE INTO Land( LandID,Name)VALUES ('SG','Singapur');
MERGE INTO Land( LandID,Name)VALUES ('SX','Sint Maarten');
MERGE INTO Land( LandID,Name)VALUES ('SK','Slowakei');
MERGE INTO Land( LandID,Name)VALUES ('SI','Slowenien');
MERGE INTO Land( LandID,Name)VALUES ('SO','Somalia');
MERGE INTO Land( LandID,Name)VALUES ('ES','Spanien');
MERGE INTO Land( LandID,Name)VALUES ('SJ','Spitzbergen');
MERGE INTO Land( LandID,Name)VALUES ('LK','Sri Lanka');
MERGE INTO Land( LandID,Name)VALUES ('BL','St. Barthélemy');
MERGE INTO Land( LandID,Name)VALUES ('KN','St. Kitts und Nevis');
MERGE INTO Land( LandID,Name)VALUES ('LC','St. Lucia');
MERGE INTO Land( LandID,Name)VALUES ('PM','St. Pierre und Miquelon');
MERGE INTO Land( LandID,Name)VALUES ('VC','St. Vincent und die Grenadinen');
MERGE INTO Land( LandID,Name)VALUES ('ZA','Südafrika');
MERGE INTO Land( LandID,Name)VALUES ('SD','Sudan');
MERGE INTO Land( LandID,Name)VALUES ('GS','Südgeorgien und die Südlichen Sandwichinseln');
MERGE INTO Land( LandID,Name)VALUES ('SS','Südsudan');
MERGE INTO Land( LandID,Name)VALUES ('SR','Suriname');
MERGE INTO Land( LandID,Name)VALUES ('SY','Syrien');
MERGE INTO Land( LandID,Name)VALUES ('TJ','Tadschikistan');
MERGE INTO Land( LandID,Name)VALUES ('TW','Taiwan');
MERGE INTO Land( LandID,Name)VALUES ('TZ','Tansania');
MERGE INTO Land( LandID,Name)VALUES ('TH','Thailand');
MERGE INTO Land( LandID,Name)VALUES ('TL','Timor-Leste');
MERGE INTO Land( LandID,Name)VALUES ('TG','Togo');
MERGE INTO Land( LandID,Name)VALUES ('TK','Tokelau');
MERGE INTO Land( LandID,Name)VALUES ('TO','Tonga');
MERGE INTO Land( LandID,Name)VALUES ('TT','Trinidad und Tobago');
MERGE INTO Land( LandID,Name)VALUES ('TD','Tschad');
MERGE INTO Land( LandID,Name)VALUES ('CZ','Tschechische Republik');
MERGE INTO Land( LandID,Name)VALUES ('TN','Tunesien');
MERGE INTO Land( LandID,Name)VALUES ('TR','Türkei');
MERGE INTO Land( LandID,Name)VALUES ('TM','Turkmenistan');
MERGE INTO Land( LandID,Name)VALUES ('TC','Turks- und Caicosinseln');
MERGE INTO Land( LandID,Name)VALUES ('TV','Tuvalu');
MERGE INTO Land( LandID,Name)VALUES ('UG','Uganda');
MERGE INTO Land( LandID,Name)VALUES ('UA','Ukraine');
MERGE INTO Land( LandID,Name)VALUES ('HU','Ungarn');
MERGE INTO Land( LandID,Name)VALUES ('UY','Uruguay');
MERGE INTO Land( LandID,Name)VALUES ('UZ','Usbekistan');
MERGE INTO Land( LandID,Name)VALUES ('VU','Vanuatu');
MERGE INTO Land( LandID,Name)VALUES ('VA','Vatikanstadt');
MERGE INTO Land( LandID,Name)VALUES ('VE','Venezuela');
MERGE INTO Land( LandID,Name)VALUES ('AE','Vereinigte Arabische Emirate');
MERGE INTO Land( LandID,Name)VALUES ('US','Vereinigte Staaten');
MERGE INTO Land( LandID,Name)VALUES ('VN','Vietnam');
MERGE INTO Land( LandID,Name)VALUES ('WF','Wallis und Futuna');
MERGE INTO Land( LandID,Name)VALUES ('CX','Weihnachtsinsel');
MERGE INTO Land( LandID,Name)VALUES ('PS','Westjordanland, Gazastreifen');
MERGE INTO Land( LandID,Name)VALUES ('EH','Westsahara');
MERGE INTO Land( LandID,Name)VALUES ('CF','Zentralafrikanische Republik');
MERGE INTO Land( LandID,Name)VALUES ('CY','Zypern');
