CREATE TABLE Land (LandID varchar(254) NOT NULL, Name varchar(254), PRIMARY KEY (LandID));

CREATE TABLE Stadt (PLZ int NOT NULL, Ort varchar(254), Land varchar(254), PRIMARY KEY (PLZ), FOREIGN KEY (Land) REFERENCES Land(LandID));

CREATE TABLE Krankenkasse (KrankenkassenNr varchar(254) NOT NULL, Name varchar(254), Starsse varchar(254), PLZ int, TelefonNr varchar(254), Email varchar(254), PRIMARY KEY (KrankenkassenNr), FOREIGN KEY (PLZ) REFERENCES Stadt(PLZ));

CREATE TABLE Kunde (KundenNr int NOT NULL, Anrede varchar(254), Name varchar(254), Vorname varchar(254), Strasse varchar(254), HausNr varchar(254), PLZ Int, Geburtsdatum date, TelefonNr varchar(254), Handy varchar(254), EMail varchar(254), KrankenkassenNr varchar(254), VersicherungsNr varchar(254), Gueltigkeit date, Bemerkung varchar(254),PRIMARY KEY (KundenNr), FOREIGN KEY (PLZ) REFERENCES Stadt(PLZ), FOREIGN KEY (KrankenkassenNr) REFERENCES Krankenkasse(KrankenkassenNr));

CREATE TABLE Firmenstamm (AugenoptikerIKNr varchar(254) NOT NULL, Steuernummer varchar(254), Geschaeftsname varchar(254), Bankverbindung varchar(254), Strasse varchar(254), HausNr varchar(254), PLZ int, TelefonNr varchar(254), Inhabername varchar(254), Inhabervorname varchar(254), PRIMARY KEY (AugenoptikerIKNr), FOREIGN KEY (PLZ) REFERENCES Stadt(PLZ));

CREATE TABLE Mail (EMail varchar(254) NOT NULL, Benutzername varchar(254), Passwort varchar(254), SMTPServer varchar(254), SMTPPort int, SMTPAuthentifizierung bit, PRIMARY KEY (Email));

CREATE TABLE Abrechnungsart (ID int NOT NULL, Art varchar(254), PRIMARY KEY (ID));

CREATE TABLE Mitarbeiter (MitarbeiterNr int NOT NULL, Name varchar(254), Vorname varchar(254), Strasse varchar(254), HausNr varchar(254), PLZ int, TelefonNr varchar(254), Handy varchar(254), Email varchar(254), Geburtsdatum date, PRIMARY KEY (MitarbeiterNr), FOREIGN KEY (PLZ) REFERENCES Stadt(PLZ));

CREATE TABLE Arzt (ArztNr int NOT NULL, Name varchar(254), Vorname varchar(254), Strasse varchar(254), HausNr varchar(254), PLZ int, TelefonNr varchar(254), Handy varchar(254), Email varchar(254), PRIMARY KEY (ArztNr), FOREIGN KEY (PLZ) REFERENCES Stadt(PLZ));

CREATE TABLE Refraktion_durchgefuert (RefraktionsNr int NOT NULL, MitarbeiterNr int, ArztNr int, PRIMARY KEY (RefraktionsNr), FOREIGN KEY (MitarbeiterNr) REFERENCES Mitarbeiter (MitarbeiterNr), FOREIGN KEY (ArztNr) REFERENCES Arzt(ArztNr));

CREATE TABLE Auftrag (Auftragsnummer int NOT NULL, AbrechnungsID varchar(254), Rezepturvorhanden bit, Womit varchar(254), Wann varchar(254), Fertig bit, Abgeholt bit, Bezahlt bit, Auftragsbestaetigung varchar(254), Rechnung varchar(254), ErsteMahnung bit, ZweiteMahnung bit, DritteMahnung bit, KundenNr int, Datum date, Werkstatt int, Berater int, Refraktion int, PRIMARY KEY (Auftragsnummer), FOREIGN KEY (KundenNr) REFERENCES Kunde(KundenNr), FOREIGN KEY (Berater) REFERENCES Mitarbeiter(MitarbeiterNr), FOREIGN KEY (Werkstatt) REFERENCES Mitarbeiter(MitarbeiterNr), FOREIGN KEY (Refraktion) REFERENCES Refraktion_durchgefuert(RefraktionsNr));

CREATE TABLE Auftragsartikel (AuftragsNr int NOT NULL, SehhilfeID int NOT NULL, SehhilfenArt int, PRIMARY KEY (AuftragsNr, SehhilfeID));

CREATE TABLE Farbe (FarbeID int NOT NULL, Bezeichnung varchar(254), Info varchar(254), PRIMARY KEY (FarbeID));

CREATE TABLE Lieferant (LieferantID int NOT NULL, Name varchar(254), Strasse varchar(254), PLZ int, TelefonNr varchar(254),  PRIMARY KEY (LieferantID), FOREIGN KEY (PLZ) REFERENCES Stadt(PLZ));

CREATE TABLE Material (MaterialID int NOT NULL, Bezeichung varchar(254), Info varchar(254), PRIMARY KEY (MaterialID));

CREATE TABLE Refraktion (RefraktionID int NOT NULL, Sph float, Cyl float, Ach int, Adds float, Pris float, Bas int, Visus float, PRIMARY KEY (RefraktionID));

CREATE TABLE Artikelart (ArtID int NOT NULL, Bezeichnung varchar(254), PRIMARY KEY (ArtID));

CREATE TABLE Artikel (ArtikelNr int NOT NULL, Bezeichnung varchar(254), Artikelart varchar(254), Material int, Farbe int, Einkaufspreis float, Verkaufspreis float, Lieferant int, PRIMARY KEY (ArtikelNr), FOREIGN KEY (Material) REFERENCES Material(MaterialID), FOREIGN KEY (Farbe) REFERENCES Farbe(FarbeID), FOREIGN KEY (Lieferant) REFERENCES Lieferant(LieferantID));

CREATE TABLE Glaeser (ArtikelNr int NOT NULL, Art int NOT NULL, Werte varchar(254), Material int, Farbe int, Einkaufspreis float, Verkaufspreis float, Lieferant int, PRIMARY KEY (ArtikelNr,Art), FOREIGN KEY (Art) REFERENCES Artikelart(ArtID),  FOREIGN KEY (Werte) REFERENCES Refraktion(RefraktionID), FOREIGN KEY (Material) REFERENCES Material(MaterialID), FOREIGN KEY (Farbe) REFERENCES Farbe(FarbeID), FOREIGN KEY (Lieferant) REFERENCES Lieferant(LieferantID));

CREATE TABLE Fassungen (ArtikelNr int NOT NULL, Art int NOT NULL, Material int, Farbe int, Einkaufspreis float, Verkaufspreis float, Lieferant int, PRIMARY KEY (ArtikelNr,Art), FOREIGN KEY (Art) REFERENCES Artikelart (ArtID), FOREIGN KEY (Material) REFERENCES Material(MaterialID), FOREIGN KEY (Farbe) REFERENCES Farbe(FarbeID), FOREIGN KEY (Lieferant) REFERENCES Lieferant(LieferantID));

CREATE TABLE Kontaktlinsen (ArtikelNr int NOT NULL, Art varchar(254) NOT NULL, Material int, Farbe int, Einkaufspreis float, Verkaufspreis float, Lieferant int, PRIMARY KEY (ArtikelNr,Art), FOREIGN KEY (Art) REFERENCES Artikelart(ArtID), FOREIGN KEY (Material) REFERENCES Material(MaterialID), FOREIGN KEY (Farbe) REFERENCES Farbe(FarbeID), FOREIGN KEY (Lieferant) REFERENCES Lieferant(LieferantID));

CREATE TABLE Brille (BrillenID int NOT NULL, GlasArtikelIDLinks int, GlasArtikelIDRechts int, FassungsArtikelID int, PRIMARY KEY (BrillenID), FOREIGN KEY (GlasArtikelIDLinks) REFERENCES Artikel (ArtikelNr), FOREIGN KEY (GlasArtikelIDRechts) REFERENCES Artikel(ArtikelNr), FOREIGN KEY (FassungsArtikelID) REFERENCES Artikel(ArtikelNr));


INSERT INTO Land( LandID,Name)VALUES ('AF','Afghanistan');
INSERT INTO Land( LandID,Name)VALUES ('EG','Ägypten');
INSERT INTO Land( LandID,Name)VALUES ('AL','Albanien');
INSERT INTO Land( LandID,Name)VALUES ('DZ','Algerien');
INSERT INTO Land( LandID,Name)VALUES ('VI','Amerikanische Jungferninseln');
INSERT INTO Land( LandID,Name)VALUES ('AS','Amerikanisch-Samoa');
INSERT INTO Land( LandID,Name)VALUES ('AD','Andorra');
INSERT INTO Land( LandID,Name)VALUES ('AO','Angola');
INSERT INTO Land( LandID,Name)VALUES ('AI','Anguilla');
INSERT INTO Land( LandID,Name)VALUES ('AG','Antigua und Barbuda');
INSERT INTO Land( LandID,Name)VALUES ('GQ','Äquatorialguinea');
INSERT INTO Land( LandID,Name)VALUES ('AR','Argentinien');
INSERT INTO Land( LandID,Name)VALUES ('AM','Armenien');
INSERT INTO Land( LandID,Name)VALUES ('AW','Aruba');
INSERT INTO Land( LandID,Name)VALUES ('AZ','Aserbaidschan');
INSERT INTO Land( LandID,Name)VALUES ('ET','Äthiopien');
INSERT INTO Land( LandID,Name)VALUES ('AU','Australien');
INSERT INTO Land( LandID,Name)VALUES ('BS','Bahamas');
INSERT INTO Land( LandID,Name)VALUES ('BH','Bahrain');
INSERT INTO Land( LandID,Name)VALUES ('BD','Bangladesch');
INSERT INTO Land( LandID,Name)VALUES ('BB','Barbados');
INSERT INTO Land( LandID,Name)VALUES ('BY','Belarus');
INSERT INTO Land( LandID,Name)VALUES ('BE','Belgien');
INSERT INTO Land( LandID,Name)VALUES ('BZ','Belize');
INSERT INTO Land( LandID,Name)VALUES ('BJ','Benin');
INSERT INTO Land( LandID,Name)VALUES ('BM','Bermuda');
INSERT INTO Land( LandID,Name)VALUES ('BT','Bhutan');
INSERT INTO Land( LandID,Name)VALUES ('BO','Bolivien');
INSERT INTO Land( LandID,Name)VALUES ('BQ','Bonaire, Saba, Sint Eustatius');
INSERT INTO Land( LandID,Name)VALUES ('BA','Bosnien und Herzegowina');
INSERT INTO Land( LandID,Name)VALUES ('BW','Botsuana');
INSERT INTO Land( LandID,Name)VALUES ('BR','Brasilien');
INSERT INTO Land( LandID,Name)VALUES ('VG','Britische Jungferninseln');
INSERT INTO Land( LandID,Name)VALUES ('BN','Brunei Darussalam');
INSERT INTO Land( LandID,Name)VALUES ('BG','Bulgarien');
INSERT INTO Land( LandID,Name)VALUES ('BF','Burkina Faso');
INSERT INTO Land( LandID,Name)VALUES ('BI','Burundi');
INSERT INTO Land( LandID,Name)VALUES ('CV','Cabo Verde');
INSERT INTO Land( LandID,Name)VALUES ('CL','Chile');
INSERT INTO Land( LandID,Name)VALUES ('CN','China');
INSERT INTO Land( LandID,Name)VALUES ('CK','Cookinseln');
INSERT INTO Land( LandID,Name)VALUES ('CR','Costa Rica');
INSERT INTO Land( LandID,Name)VALUES ('CI','Côte d Ivoire');
INSERT INTO Land( LandID,Name)VALUES ('CW','Curaçao');
INSERT INTO Land( LandID,Name)VALUES ('DK','Dänemark');
INSERT INTO Land( LandID,Name)VALUES ('DE','Deutschland');
INSERT INTO Land( LandID,Name)VALUES ('DM','Dominica');
INSERT INTO Land( LandID,Name)VALUES ('DO','Dominikanische Republik');
INSERT INTO Land( LandID,Name)VALUES ('DJ','Dschibuti');
INSERT INTO Land( LandID,Name)VALUES ('EC','Ecuador');
INSERT INTO Land( LandID,Name)VALUES ('SV','El Salvador');
INSERT INTO Land( LandID,Name)VALUES ('ER','Eritrea');
INSERT INTO Land( LandID,Name)VALUES ('EE','Estland');
INSERT INTO Land( LandID,Name)VALUES ('SZ','Eswatini');
INSERT INTO Land( LandID,Name)VALUES ('FK','Falklandinseln');
INSERT INTO Land( LandID,Name)VALUES ('FO','Färöer');
INSERT INTO Land( LandID,Name)VALUES ('FJ','Fidschi');
INSERT INTO Land( LandID,Name)VALUES ('FI','Finnland');
INSERT INTO Land( LandID,Name)VALUES ('FR','Frankreich');
INSERT INTO Land( LandID,Name)VALUES ('GF','Französisch-Guayana');
INSERT INTO Land( LandID,Name)VALUES ('PF','Französisch-Polynesien');
INSERT INTO Land( LandID,Name)VALUES ('GA','Gabun');
INSERT INTO Land( LandID,Name)VALUES ('GM','Gambia');
INSERT INTO Land( LandID,Name)VALUES ('GE','Georgien');
INSERT INTO Land( LandID,Name)VALUES ('GH','Ghana');
INSERT INTO Land( LandID,Name)VALUES ('GI','Gibraltar');
INSERT INTO Land( LandID,Name)VALUES ('GD','Grenada');
INSERT INTO Land( LandID,Name)VALUES ('GR','Griechenland');
INSERT INTO Land( LandID,Name)VALUES ('GL','Grönland');
INSERT INTO Land( LandID,Name)VALUES ('GB','Großbritannien');
INSERT INTO Land( LandID,Name)VALUES ('GP','Guadeloupe');
INSERT INTO Land( LandID,Name)VALUES ('GU','Guam');
INSERT INTO Land( LandID,Name)VALUES ('GT','Guatemala');
INSERT INTO Land( LandID,Name)VALUES ('GG','Guernsey');
INSERT INTO Land( LandID,Name)VALUES ('GN','Guinea');
INSERT INTO Land( LandID,Name)VALUES ('GW','Guinea-Bissau');
INSERT INTO Land( LandID,Name)VALUES ('GY','Guyana');
INSERT INTO Land( LandID,Name)VALUES ('HT','Haiti');
INSERT INTO Land( LandID,Name)VALUES ('HN','Honduras');
INSERT INTO Land( LandID,Name)VALUES ('HK','Hongkong');
INSERT INTO Land( LandID,Name)VALUES ('IN','Indien');
INSERT INTO Land( LandID,Name)VALUES ('ID','Indonesien');
INSERT INTO Land( LandID,Name)VALUES ('IM','Insel Man');
INSERT INTO Land( LandID,Name)VALUES ('IQ','Irak');
INSERT INTO Land( LandID,Name)VALUES ('IR','Iran');
INSERT INTO Land( LandID,Name)VALUES ('IE','Irland');
INSERT INTO Land( LandID,Name)VALUES ('IS','Island');
INSERT INTO Land( LandID,Name)VALUES ('IL','Israel');
INSERT INTO Land( LandID,Name)VALUES ('IT','Italien');
INSERT INTO Land( LandID,Name)VALUES ('JM','Jamaika');
INSERT INTO Land( LandID,Name)VALUES ('JP','Japan');
INSERT INTO Land( LandID,Name)VALUES ('YE','Jemen');
INSERT INTO Land( LandID,Name)VALUES ('JE','Jersey');
INSERT INTO Land( LandID,Name)VALUES ('JO','Jordanien');
INSERT INTO Land( LandID,Name)VALUES ('KY','Kaimaninseln');
INSERT INTO Land( LandID,Name)VALUES ('KH','Kambodscha');
INSERT INTO Land( LandID,Name)VALUES ('CM','Kamerun');
INSERT INTO Land( LandID,Name)VALUES ('CA','Kanada');
INSERT INTO Land( LandID,Name)VALUES ('KZ','Kasachstan');
INSERT INTO Land( LandID,Name)VALUES ('QA','Katar');
INSERT INTO Land( LandID,Name)VALUES ('KE','Kenia');
INSERT INTO Land( LandID,Name)VALUES ('KG','Kirgisistan');
INSERT INTO Land( LandID,Name)VALUES ('KI','Kiribati');
INSERT INTO Land( LandID,Name)VALUES ('CC','Kokosinseln (Keelinginseln)');
INSERT INTO Land( LandID,Name)VALUES ('CO','Kolumbien');
INSERT INTO Land( LandID,Name)VALUES ('KM','Komoren');
INSERT INTO Land( LandID,Name)VALUES ('CG','Kongo');
INSERT INTO Land( LandID,Name)VALUES ('CD','Kongo, Demokratische Republik');
INSERT INTO Land( LandID,Name)VALUES ('KP','Korea, Demokratische Volksrepublik');
INSERT INTO Land( LandID,Name)VALUES ('KR','Korea, Republik');
INSERT INTO Land( LandID,Name)VALUES ('HR','Kroatien');
INSERT INTO Land( LandID,Name)VALUES ('CU','Kuba');
INSERT INTO Land( LandID,Name)VALUES ('KW','Kuwait');
INSERT INTO Land( LandID,Name)VALUES ('LA','Laos');
INSERT INTO Land( LandID,Name)VALUES ('LS','Lesotho');
INSERT INTO Land( LandID,Name)VALUES ('LV','Lettland');
INSERT INTO Land( LandID,Name)VALUES ('LB','Libanon');
INSERT INTO Land( LandID,Name)VALUES ('LR','Liberia');
INSERT INTO Land( LandID,Name)VALUES ('LY','Libyen');
INSERT INTO Land( LandID,Name)VALUES ('LI','Liechtenstein');
INSERT INTO Land( LandID,Name)VALUES ('LT','Litauen');
INSERT INTO Land( LandID,Name)VALUES ('LU','Luxemburg');
INSERT INTO Land( LandID,Name)VALUES ('MO','Macau');
INSERT INTO Land( LandID,Name)VALUES ('MG','Madagaskar');
INSERT INTO Land( LandID,Name)VALUES ('MW','Malawi');
INSERT INTO Land( LandID,Name)VALUES ('MY','Malaysia');
INSERT INTO Land( LandID,Name)VALUES ('MV','Malediven');
INSERT INTO Land( LandID,Name)VALUES ('ML','Mali');
INSERT INTO Land( LandID,Name)VALUES ('MT','Malta');
INSERT INTO Land( LandID,Name)VALUES ('MA','Marokko');
INSERT INTO Land( LandID,Name)VALUES ('MH','Marshallinseln');
INSERT INTO Land( LandID,Name)VALUES ('MQ','Martinique');
INSERT INTO Land( LandID,Name)VALUES ('MR','Mauretanien');
INSERT INTO Land( LandID,Name)VALUES ('MU','Mauritius');
INSERT INTO Land( LandID,Name)VALUES ('YT','Mayotte');
INSERT INTO Land( LandID,Name)VALUES ('MX','Mexiko');
INSERT INTO Land( LandID,Name)VALUES ('','Midway');
INSERT INTO Land( LandID,Name)VALUES ('FM','Mikronesien');
INSERT INTO Land( LandID,Name)VALUES ('MD','Moldau');
INSERT INTO Land( LandID,Name)VALUES ('MC','Monaco');
INSERT INTO Land( LandID,Name)VALUES ('MN','Mongolei');
INSERT INTO Land( LandID,Name)VALUES ('ME','Montenegro');
INSERT INTO Land( LandID,Name)VALUES ('MS','Montserrat');
INSERT INTO Land( LandID,Name)VALUES ('MZ','Mosambik');
INSERT INTO Land( LandID,Name)VALUES ('MM','Myanmar');
INSERT INTO Land( LandID,Name)VALUES ('NA','Namibia');
INSERT INTO Land( LandID,Name)VALUES ('NR','Nauru');
INSERT INTO Land( LandID,Name)VALUES ('NP','Nepal');
INSERT INTO Land( LandID,Name)VALUES ('NC','Neukaledonien');
INSERT INTO Land( LandID,Name)VALUES ('NZ','Neuseeland');
INSERT INTO Land( LandID,Name)VALUES ('NI','Nicaragua');
INSERT INTO Land( LandID,Name)VALUES ('NL','Niederlande');
INSERT INTO Land( LandID,Name)VALUES ('NE','Niger');
INSERT INTO Land( LandID,Name)VALUES ('NG','Nigeria');
INSERT INTO Land( LandID,Name)VALUES ('NU','Niue');
INSERT INTO Land( LandID,Name)VALUES ('MP','Nördliche Marianen');
INSERT INTO Land( LandID,Name)VALUES ('MK','Nordmazedonien');
INSERT INTO Land( LandID,Name)VALUES ('NF','Norfolkinsel');
INSERT INTO Land( LandID,Name)VALUES ('NO','Norwegen');
INSERT INTO Land( LandID,Name)VALUES ('OM','Oman');
INSERT INTO Land( LandID,Name)VALUES ('AT','Österreich');
INSERT INTO Land( LandID,Name)VALUES ('PK','Pakistan');
INSERT INTO Land( LandID,Name)VALUES ('PW','Palau');
INSERT INTO Land( LandID,Name)VALUES ('PA','Panama');
INSERT INTO Land( LandID,Name)VALUES ('PG','Papua-Neuguinea');
INSERT INTO Land( LandID,Name)VALUES ('PY','Paraguay');
INSERT INTO Land( LandID,Name)VALUES ('PE','Peru');
INSERT INTO Land( LandID,Name)VALUES ('PH','Philippinen');
INSERT INTO Land( LandID,Name)VALUES ('PN','Pitcairninseln');
INSERT INTO Land( LandID,Name)VALUES ('PL','Polen');
INSERT INTO Land( LandID,Name)VALUES ('PT','Portugal');
INSERT INTO Land( LandID,Name)VALUES ('PR','Puerto Rico');
INSERT INTO Land( LandID,Name)VALUES ('RE','Réunion');
INSERT INTO Land( LandID,Name)VALUES ('RW','Ruanda');
INSERT INTO Land( LandID,Name)VALUES ('RO','Rumänien');
INSERT INTO Land( LandID,Name)VALUES ('RU','Russische Föderation');
INSERT INTO Land( LandID,Name)VALUES ('MF','Saint-Martin');
INSERT INTO Land( LandID,Name)VALUES ('SB','Salomonen');
INSERT INTO Land( LandID,Name)VALUES ('ZM','Sambia');
INSERT INTO Land( LandID,Name)VALUES ('WS','Samoa');
INSERT INTO Land( LandID,Name)VALUES ('SM','San Marino');
INSERT INTO Land( LandID,Name)VALUES ('ST','São Tomé und Príncipe');
INSERT INTO Land( LandID,Name)VALUES ('SA','Saudi-Arabien');
INSERT INTO Land( LandID,Name)VALUES ('SE','Schweden');
INSERT INTO Land( LandID,Name)VALUES ('CH','Schweiz');
INSERT INTO Land( LandID,Name)VALUES ('SN','Senegal');
INSERT INTO Land( LandID,Name)VALUES ('RS','Serbien');
INSERT INTO Land( LandID,Name)VALUES ('SC','Seychellen');
INSERT INTO Land( LandID,Name)VALUES ('SL','Sierra Leone');
INSERT INTO Land( LandID,Name)VALUES ('ZW','Simbabwe');
INSERT INTO Land( LandID,Name)VALUES ('SG','Singapur');
INSERT INTO Land( LandID,Name)VALUES ('SX','Sint Maarten');
INSERT INTO Land( LandID,Name)VALUES ('SK','Slowakei');
INSERT INTO Land( LandID,Name)VALUES ('SI','Slowenien');
INSERT INTO Land( LandID,Name)VALUES ('SO','Somalia');
INSERT INTO Land( LandID,Name)VALUES ('ES','Spanien');
INSERT INTO Land( LandID,Name)VALUES ('SJ','Spitzbergen');
INSERT INTO Land( LandID,Name)VALUES ('LK','Sri Lanka');
INSERT INTO Land( LandID,Name)VALUES ('BL','St. Barthélemy');
INSERT INTO Land( LandID,Name)VALUES ('KN','St. Kitts und Nevis');
INSERT INTO Land( LandID,Name)VALUES ('LC','St. Lucia');
INSERT INTO Land( LandID,Name)VALUES ('PM','St. Pierre und Miquelon');
INSERT INTO Land( LandID,Name)VALUES ('VC','St. Vincent und die Grenadinen');
INSERT INTO Land( LandID,Name)VALUES ('ZA','Südafrika');
INSERT INTO Land( LandID,Name)VALUES ('SD','Sudan');
INSERT INTO Land( LandID,Name)VALUES ('GS','Südgeorgien und die Südlichen Sandwichinseln');
INSERT INTO Land( LandID,Name)VALUES ('SS','Südsudan');
INSERT INTO Land( LandID,Name)VALUES ('SR','Suriname');
INSERT INTO Land( LandID,Name)VALUES ('SY','Syrien');
INSERT INTO Land( LandID,Name)VALUES ('TJ','Tadschikistan');
INSERT INTO Land( LandID,Name)VALUES ('TW','Taiwan');
INSERT INTO Land( LandID,Name)VALUES ('TZ','Tansania');
INSERT INTO Land( LandID,Name)VALUES ('TH','Thailand');
INSERT INTO Land( LandID,Name)VALUES ('TL','Timor-Leste');
INSERT INTO Land( LandID,Name)VALUES ('TG','Togo');
INSERT INTO Land( LandID,Name)VALUES ('TK','Tokelau');
INSERT INTO Land( LandID,Name)VALUES ('TO','Tonga');
INSERT INTO Land( LandID,Name)VALUES ('TT','Trinidad und Tobago');
INSERT INTO Land( LandID,Name)VALUES ('TD','Tschad');
INSERT INTO Land( LandID,Name)VALUES ('CZ','Tschechische Republik');
INSERT INTO Land( LandID,Name)VALUES ('TN','Tunesien');
INSERT INTO Land( LandID,Name)VALUES ('TR','Türkei');
INSERT INTO Land( LandID,Name)VALUES ('TM','Turkmenistan');
INSERT INTO Land( LandID,Name)VALUES ('TC','Turks- und Caicosinseln');
INSERT INTO Land( LandID,Name)VALUES ('TV','Tuvalu');
INSERT INTO Land( LandID,Name)VALUES ('UG','Uganda');
INSERT INTO Land( LandID,Name)VALUES ('UA','Ukraine');
INSERT INTO Land( LandID,Name)VALUES ('HU','Ungarn');
INSERT INTO Land( LandID,Name)VALUES ('UY','Uruguay');
INSERT INTO Land( LandID,Name)VALUES ('UZ','Usbekistan');
INSERT INTO Land( LandID,Name)VALUES ('VU','Vanuatu');
INSERT INTO Land( LandID,Name)VALUES ('VA','Vatikanstadt');
INSERT INTO Land( LandID,Name)VALUES ('VE','Venezuela');
INSERT INTO Land( LandID,Name)VALUES ('AE','Vereinigte Arabische Emirate');
INSERT INTO Land( LandID,Name)VALUES ('US','Vereinigte Staaten');
INSERT INTO Land( LandID,Name)VALUES ('VN','Vietnam');
INSERT INTO Land( LandID,Name)VALUES ('WF','Wallis und Futuna');
INSERT INTO Land( LandID,Name)VALUES ('CX','Weihnachtsinsel');
INSERT INTO Land( LandID,Name)VALUES ('PS','Westjordanland, Gazastreifen');
INSERT INTO Land( LandID,Name)VALUES ('EH','Westsahara');
INSERT INTO Land( LandID,Name)VALUES ('CF','Zentralafrikanische Republik');
INSERT INTO Land( LandID,Name)VALUES ('CY','Zypern');